- .buildkite/ct.version.yaml
- .buildkite/ct.yaml
- .buildkite/pipeline.yaml
- .buildkite/scripts/pipeline.sh
Adds a specific step for testing the version of the chart, allows for some concurrency for building the charts as well as ensures the order is executed correctly, forces deletion of the gh-pages branch locally to hopefully aleviate an out-of-sync git error, and adds a CT_BYPASS env var for future use and testing.
> ci: refactor pipeline

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/configMap.yaml
- charts/authelia/templates/deployment.yaml
- charts/authelia/templates/rbac/serviceAccount.yaml
- charts/authelia/templates/secret.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This commit adds the HashiCorp Vault injector configuration. Additionally it refactors the ConfigMap and Secret generation methods. It introduces several major changes to the values.yaml which should be considered breaking. Several providers now have an 'enabled' option and some have 'enabledSecret'. How they operate is 'enabled' renders the values of the section in the ConfigMap, and the enabledSecret option forces the secret to be used - this is used for redis and SMTP. Lastly it removes the commented sections of a majority of the commented configuration in values.yaml making it more compatible with various GitOps solutions.
Related to #12
> feat(authelia): hashicorp vault injector

- .buildkite/pipeline.yaml
Only add the wait step to the pipeline when it's needed, i.e. when the branch is master and there are changes to the charts.
> ci: only wait on master with changes

- .buildkite/README.md
- .buildkite/hooks/pre-command
- .buildkite/pipeline.yaml
This should hopefully fix all remaining CI/CD chart releaser index issues.
> ci: ensure .cr-index exists, remove block, and update docs

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This fixes the env indent when additioanl env is defined. Additionally it adds blank defaults for various commented values which should work similar to if they did not exist in most instances, it just adds the ability in tools like argo-cd to see all of the values in advance.
> fix(authelia): env indent and undefined blank values

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
Previously this would render nodes with a list on a new line instead of rendering it on the same line. This change means it wont be rendered at all.
> fix(authelia): only render redis ha nodes when defined

- charts/authelia/Chart.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This just allows argo-cd and similar tools to auto-detect additional values without defining defaults.
> fix: missing blank defaults

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/deployment.yaml
This adds the checksum of the generated ConfigMap and Secret to the deployment templates metadata annotations. This will cause the deployment to be updated triggering a RollingUpdate or Recreate.
> feat(authelia): add config checksums to pod template meta

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This is because the Authelia binary no longer supports bypass with an empty ACL. This prevents an error when deploying the chart. Additionally in older versions prevents an insecure and ineffectual configuration.
> fix(authelia): force one_factor or above with empty acl

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This is so the username is only rendered if the username is not an empty string. Additionally it makes the default an empty string. This is so when users do not have the new redis v6 authentication enabled they can still use pre-v6 redis authentication.
> fix(authelia): make redis username actually optional

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This makes the indentation uniform with other areas of the configmap.
> fix(authelia): access control indentation

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
This prevents the LDAP and STORAGE secret keys being imported by the secrets volume when they are not enabled.
> fix(authelia): secret volume includes non-existant keys

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/secret.yaml
This prevents the SMTP secret keys being imported by the secrets volume when it is not enabled.
> fix(authelia): secret volume includes non-existant smtp key

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This is so the LDAP properties are only rendered when LDAP is enabled. A logic error in where the end block was placed caused an unwanted behaviour.
> fix(authelia): incorrect end block in configmap

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/configMap.yaml
- charts/authelia/templates/deployment.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
The mount path for the PVC was being overridden by the mount path for the configmap. This resolves this issue and also moves all non-dynamic data (i.e. certs, cecrets, configmaps) out of the config volume.
> fix(authelia): incorrect mount path for configmap

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
Bumps the version to latest and makes the default tag the .Chart.AppVersion value in preparation for removing it from the chart .Values and using the .Values.image.tag as an override.
> feat(authelia): version 4.29.1

- charts/authelia/Chart.yaml
- charts/authelia/templates/NOTES.txt
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/ingress.yaml
- charts/authelia/templates/traefikCRD/ingressRoute.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
Allows users to utilize the KubernetesIngress provider with Traefik and still create the CRD's for the middlewares etc.
> feat(authelia): add option to use regular ingress with traefikcrd

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/networkPolicy.yaml
Capabilities generally can be detected via helm suffixed with their kind, however GitOps utilities like ArgoCD and flux do not forward these capabilities to the helm binary correctly, thus you have to fall back on semverCompare. This change should accurately detect based on version and should work for alpha / beta releases.
> feat(authelia): add fallback to semver compare for caps

- charts/authelia/Chart.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
Makes the TraefikCRD IngressRoute the default when TraefikCRD is enabled.
> fix(authelia): invalid ingress default

- charts/authelia/Chart.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
Uses ghcr.io as the default registry for images.
> feat(authelia): make ghcr.io the default registry

- charts/authelia/Chart.yaml
- charts/authelia/templates/NOTES.txt
- charts/authelia/templates/_helpers.tpl
Fixes the order of the @kubernetescrd name of the annotations for the Ingress type.
> fix(authelia): fix incorrect kubernetescrd namespace/object order

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
This PR fixes indentation on `extraVolumes` and `extraVolumeMounts` and therefor the following error messages which would appear when using these values:
```
Error: YAML parse error on authelia/templates/deployment.yaml: error converting YAML to JSON: yaml: line 98: mapping values are not allowed in this context 
Error: YAML parse error on authelia/templates/deployment.yaml: error converting YAML to JSON: yaml: line 113: mapping values are not allowed in this context
```
> fixing extraVolumes and extraVolumeMounts indentation

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This was a typo which would cause the OIDC configuration to not honor the policy set in the values.
Fixes #74
> fix(authelia): typo in oidc client

- .buildkite/pipeline.yaml
This ensures the check for charts to package is since HEAD~1 instead of HEAD. Though I'm unsure how this is just now failing.
> build: fix ct config for release packaging

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
Disables the unused and deprecated service links functionality in k8s. It's possible looking at the change to see how to adjust the values to turn it back on, but it will not be supported in 4.30+.
> fix(authelia): disable service links

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This PR fixes a small C&P error, which breaks Authelia completely if you have set a value for `issuer`
> fix(authelia): new totp options keys

- charts/authelia/Chart.yaml
- charts/authelia/templates/secret.yaml
Fixes:
```
Error: template: authelia/templates/secret.yaml:37:86: executing "authelia/templates/secret.yaml" at <default>: wrong number of args for default: want at least 1 got 0
```
Caused by recent changes here:
https://github.com/authelia/chartrepo/commit/17e7b94bb3b11fe0e7ab1b04d37af04cd2959724#diff-9189c2f5c1b19f1988198e0c692eea37875a6bc90ce03513fbcfa995a3238b91L34
> fix(authelia): missing parenthesis around default invocation

- charts/authelia/Chart.yaml
- charts/authelia/templates/ingress.yaml
As 1.18 and 1.19 are no longer versions of k8s in the support lifecycle this makes the networking.k8s.io/v1 api version the default for ingress types.
> fix(authelia): ingress logic outdated

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
Ensures that custom annotations on the ingress completely replace any automatic ones. However it's recommended that you utilize the entryPoints and middlewares options instead.
> fix(authelia): prevent traefik auto annotations overriding custom ones

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This removes the invalid keys from 4.34.0.
> fix(authelia): skip invalid pkce keys

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This is to eliminate options in the configmap for older versions. It will take time to add these specific values.
> fix(authelia): add version override

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
Image pull secrets is placed inside Daemonset.spec.template.spec.container[0]. imagePullSecrets rather should be in spec.template.spec. imagePullSecrets
**Description of the change**
The Image pull secret is not recognized as valid configuration when placed under Daemonset.spec.template.spec.container[0]
Changing the path to Daemonset.spec.template.spec. imagePullSecrets solves the issue.
**Benefits**
Imagepull secrets works as expected.
**Signed-off-by**: Harish Desetti <desettih@gmail.com>
> fix(authelia): image pull secrets is in wrong spec

- charts/authelia/Chart.yaml
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/configMap.yaml
- charts/authelia/templates/deployment.yaml
- charts/authelia/templates/secret.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This adds several semver checks to ensure that only config values for the relevant Authelia version are rendered. This can be controlled by changing the versionOverride value otherwise it uses the chart AppVersion value.
> feat: omit config values not valid for the specific version

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This fixes an issue where the argon2 memory config is  used instead of parallelism, causing an error.
Fixes #186
> fix(authelia): argon2 memory linked to parallelism

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
Related to this startup error:
```
time="2022-11-20T15:48:18Z" level=error msg="Configuration: authentication_backend: file: password: sha2crypt: option 'iterations' is configured as '3' but must be greater than or equal to '1000'"
time="2022-11-20T15:48:18Z" level=fatal msg="Can't continue due to the errors loading the configuration"
Process finished with exit code 0
```
My `values.yaml` does not configure `sha2crypt`. The chart is rendering a default value for this section of 3 because it is pulling from the `values.yaml` incorrectly and quoting it. The value should make sense for the algorithm and it should not be quoted.
for reference:
https://www.authelia.com/reference/cli/authelia/authelia_crypto_hash_generate_sha2crypt/
> fix(authelia): sha2crypt iterations incorrectly rendered

- charts/authelia/Chart.yaml
- charts/authelia/templates/secret.yaml
This fixes an issue where the secret data for OpenID Connect 1.0 HMAC Secret and RSA Private Key are not appropriately base64 decoded, and get encoded for a second time.
Fixes #177
> fix(authelia): oidc secret data not decoded correctly

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
`configMap.session.redis.database_index` was specified in the `values.yaml` file, but its value was never used. This PR fixes that
> fix: use session.redis.database_index in ConfigMap

- charts/authelia/Chart.yaml
- charts/authelia/templates/persistentVolumeClaim.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
Hey!
For some usecases it is useful to specify a volumeName in the PVC. I for example run k8s on baremetal and use pre-created iSCSI targets as persistent volumes. Being able to specify those volume names directly would be very useful.
This shouldn't interfere with anything else as long as it is not set. Let me know what you think.
> Allow the specification of a persistent volume name

- charts/authelia/Chart.yaml
- charts/authelia/templates/service.yaml
- charts/authelia/values.yaml
Hello,
This MR allows to change the type service with `NodePort` if needed. By default, the behaviour is not changed.
My use case is that for Traefik Middleware, I need to reach Authelia internally but my Traefik instance is out of the cluster. So I required the service to be exposed by the NodePort.
> feat: allow to user NodePort type for service

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/values.yaml
This PR is exactly the same as #223, but adds Redis support from Bitnami helm charts, along with the existing MariaDB and PostgreSQL support.
Existing behaviour is retained - users have to opt in to deploying Redis.
This finally fixes #89 and #172
> Add support for integrated Redis

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This seems to be a regression with the 0.9.0 version, introduced in [the 4.38.0 update commit](https://github.com/authelia/chartrepo/blame/9fccf91dbbd19ca183f7edb1ce7a8f252c1a8335/charts/authelia/templates/configMap.yaml#L201).
Quite annoying because `inactivity` is `5 minutes` by default, leading to constant logouts.
~~I am currently targeting `0.9.0-beta3`, but I'd assume this is incorrect. Unfortunately, I couldn't find a branch for new `0.9.0` releases, please let me know which one to use and I can open a new PR.~~
~~I just noticed that 0.9 betas are actually on `master`. Hence, I've changed the base accordingly. I'll have to rebase my commits onto it tomorrow which should *hopefully* remove the extra commits there and allow a clean merge.~~
> Fix `session.remember_me` using `inactivity` value

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
Aims to implement a fix for #239
The check if TLS is enabled was missing for the storage providers.
This lead to TLS errors when connecting to local database instances:
```log
Error occurred running a startup check" error="error pinging database: TLS requested but server does not support TLS" provider=storage
```
This PR generates the CM without the TLS key for the MySQL and Postgres storage providers if TLS is not enabled.
> fix: check if storage-tls is enabled

- charts/authelia/.helmignore
- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/values.yaml
This PR adds basic support for deploying Redis, MariaDB or PostgreSQL as part of an Authelia deployment.
Typically the dependency subcharts would be integrated under the top level `mariadb:` or `postgresql:` keys, where the config can be inherited by the subcharts, and the main app (i.e. Authelia) would also draw its config from those keys. However the database config in the chart is under `storage.mysql` and `storage.postgres` and changing this would be a breaking change.
So I have added booleans `storage.redis.deploy`, `storage.mysql.deploy` and `storage.postgres.deploy` which enable the user to deploy the Bitnami subcharts. This does not affect any existing Authelia deployments. At the moment the user has to copy a few settings (e.g. credentials) from the `mariadb` section to the …
> Bundle Helm charts for Redis, MariaDB and PostgreSQL

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
This fixes an issue when setting a custom path in the values. Not adding the path to the address config creates a bunch of static path 404 errors due to them being redirected to the root path and making Authelia unusable.
> fix: add subpath to server address

- charts/authelia/Chart.yaml
- charts/authelia/templates/traefikCRD/middlewares.yaml
- charts/authelia/values.local.yaml
This fixes both the values.local.yaml and the indent for TraefikCRD ingressRoute chain before middlewares.
Fixes #250
> fix: values local example and indents

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
Without this change, templating fails when using authorization policies due to the `with` statement changing the scope of the `.` variable on following line. Fix by accessing from global scope `$.`.
> Fix templating error with authorization_policies.

- charts/authelia/Chart.yaml
- charts/authelia/templates/validations.configMap.check.yaml
configMap validation mentions a wrong helm value in its error message.
> fix: validation failure message mentioning wrong helm value

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
Fix an issue where the config dir is missing on minimal setups with 4.39.0.
> fix(authelia): config dir missing on minimal setup

- charts/authelia/Chart.yaml
- charts/authelia/templates/configMap.yaml
It seems there is a typo when generating user_attributes, where the ranged over value is not pluralised
> Fix typo referencing .Values.configMap.definitions.user_attribute

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/templates/_helpers.tpl
- charts/authelia/templates/deployment.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
This allows partially customizing the subpath of the additional secrets mounted into the container.
> fix(authelia): additional secrets path

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/files/configuration.server.endpoints.authz.yaml
This fixes an issue where the basic cache lifespan was included when using a strategy that doesn't support it, or when the basic scheme was not included.
> fix(authelia): cache lifespan included incorrectly

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/values.local.yaml
- charts/authelia/values.yaml
The LDAP default values are unhelpful and should easily permit users to either not set them or override them which is not actually the case. This fixes that issue.
> fix(authelia): ldap defaults

- charts/authelia/Chart.yaml
- charts/authelia/templates/deployment.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.schema.json
- charts/authelia/values.yaml
This PR adds support for having extra containers in the authelia pod, as briefly outlined in issue #347 
Does this make sense for this helmchart? C&C are very welcome!
> Add support for extraContainers

- charts/authelia/Chart.yaml
- charts/authelia/README.md
- charts/authelia/templates/service.yaml
- charts/authelia/values.local.yaml
- charts/authelia/values.schema.json
- charts/authelia/values.yaml
add externalTrafficPolicy option. this needed for correct IP rules. from official doc
<https://www.authelia.com/integration/kubernetes/introduction/#external-traffic-policy>
default Cluster, matching kube default
make docs && make schema
> feat(authelia): externalTrafficPolicy
