authelia/chartrepo

.buildkite/README.md
.buildkite/hooks/post-checkout
.buildkite/hooks/pre-command

This moves the pre-command hook into the repository as it's not required to run it locally for any reason.

ci: add pre-command hook

---

.buildkite/README.md
.buildkite/hooks/post-checkout

This should theoretically all that's needed.

ci: simplify the post-checkout hook and update docs

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/templates/configMap.yaml
charts/authelia/templates/deployment.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Fixes for issues mentioned at https://github.com/authelia/chartrepo/pull/16

fix(authelia): incorrect vault injector annotations and missing security context

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This is a proposal for templating secrets like mentioned at https://github.com/authelia/chartrepo/issues/12#issuecomment-811859226

feat(authelia): added vault secret template for KV v1

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl

This fixes the filename issue with redis sentinel.

fix(authelia): redis sentinel secret filename

---

.buildkite/hooks/pre-command

Updates the git user for gh-pages commits to the Authelia Bot user.

ci: use autheliabot to make commits on the gh-pages branch

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/templates/configMap.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This bumps the chart to be compatible with the same_site and oidc changes, also bumping the Authelia version to 4.28.2.

feat(authelia): samesite and oidc changes

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This updates the values files to use the v4.29.0 version.

feat(authelia): update version to v4.29.0

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This is the default of the chart templates, should also be the default for the values files.

fix(authelia): set default log level to info

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl

This is so the additional labels are indented correctly.
Fixes #55

fix(authelia): labels indent

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml

Hi,
Caught and fixed two small bugs in ldap config map today when trying to adopt the helm chart.
P.S. I bumped the chart version as well but it might be wrong if other commits will be faster.

Fixed mail_attribute & display_name_attribute in ldap configmap

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Bumps the version to the next release in Authelia's lifecycle.

feat(authelia): version 4.29.3

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Bumps the version to the next release in Authelia's lifecycle.

feat(authelia): version 4.29.4

---

charts/authelia/Chart.yaml
charts/authelia/templates/secret.yaml

This generates the secrets expected instead of blank defaults.

feat(authelia): add default oidc secrets

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Adds additional options that will be added in 4.30.0 for ease of transition.

feat(authelia): additional 4.30 compatability support

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/templates/configMap.yaml
charts/authelia/templates/deployment.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Adds full support for Authelia 4.30.0.
BREAKING CHANGE: This change breaks the old values file layout and requires you upgrade. See the chart README for details.

feat(authelia): authelia 4.30.0

---

charts/authelia/Chart.yaml
charts/authelia/templates/deployment.yaml

Fixes indentation of securityContext for pod spec.

fix(authelia): indentation of pod security context

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/templates/NOTES.txt
charts/authelia/templates/_helpers.tpl
charts/authelia/templates/configMap.yaml
charts/authelia/templates/deployment.yaml
charts/authelia/templates/secret.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This adds support for secret lookups and the upcoming 4.33.0 binary.

feat(authelia): secret lookups

---

charts/authelia/Chart.yaml
charts/authelia/templates/NOTES.txt

fix(authelia): traefik annotation string is wrong

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml

Forces the public client to not have a secret configured.
Fixes #118

fix(authelia): oidc public client

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl

Various annotations do not merge appropriately due to some bad logic.

fix(authelia): annotation merge logic

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

👋🏾 Hi again, just me plopping more Redis Sentinel username keys into yaml files 😄 
First time modifying a helm chart though, so might be worth a bit of extra scrutiny!

feat(authelia): add support for sentinel-acl auth

---

charts/authelia/Chart.yaml
charts/authelia/templates/traefikCRD/ingressRoute.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

feat(authelia): disable tlsOption

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Uses a blank image tag and instead utilizes the chart appVersion.

feat(authelia): use blank image tag

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This fixes missing values from the chart.

fix(authelia): missing vault injector values

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml

Another issue with a copy paste with the file provider.
Fixes #186

fix(authelia): argon2 memory linked to parallelism

---

charts/authelia/Chart.yaml
charts/authelia/templates/_config_auth.tpl
charts/authelia/templates/configMap.yaml

This fixes various issues surrounding the algorithm changes to the file auth backend.

fix(authelia): use templates for deprecated password alg values

---

charts/authelia/Chart.yaml
charts/authelia/templates/deployment.yaml

Adds a checksum to the deployment if the ACL is a secret.
Fixes #191

feat(authelia): acl checksum

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/templates/deployment.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Include the priority class name value.
Closes #202

feat(authelia): priority class name

---

charts/authelia/Chart.yaml
charts/authelia/README.md

chore: update deprecated documentation urls on README

---

charts/authelia/templates/_misc.tpl
charts/authelia/templates/configMap.yaml

Hi
Just a couple of small indentation fixes found while testing 4.38.0.

Indentation fixes

---

charts/authelia/Chart.yaml
charts/authelia/templates/_ingress.tpl
charts/authelia/templates/configMap.yaml

This fixes an issue where the path value for the authelia_url was ignored.
Fixes #255

fix: authelia url path

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl

Hello !
I need to set replicas to 0 for my Authelia deployment but there is an issue with the interpretation of `0` with default. it's a [known issue](https://github.com/helm/helm/issues/3164) with helm so I added this simple workaround.
Thanks for your work!

feat: handle correctly when replicas is set to 0

---

charts/authelia/Chart.yaml
charts/authelia/templates/configMap.yaml

This fixes an issue rendering the oidc authz subject.

fix(authelia): oidc authz subject rendering

---

charts/authelia/Chart.yaml
charts/authelia/templates/deployment.yaml

fix(#266): swap pod & container securityContext

---

charts/authelia/Chart.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

Fix an issue where some test variables crept into the values files.

fix(authelia): test variables included in values.yaml

---

charts/authelia/Chart.yaml
charts/authelia/files/configuration.oidc.client.yaml

This fixes an issue where the client encryption_enc values were set incorrectly.

fix(authelia): encryption enc parameters set incorrectly

---

charts/authelia/Chart.yaml
charts/authelia/files/configuration.oidc.client.yaml

This fixes an issue where the client encryption_alg values were set incorrectly.

fix(authelia): encryption alg parameters set incorrectly

---

charts/authelia/Chart.yaml
charts/authelia/templates/_helpers.tpl
charts/authelia/templates/traefikCRD/middlewares.yaml

Fixes https://github.com/authelia/chartrepo/issues/306
This PR addresses a regression in release [authelia-0.10.12](https://github.com/authelia/chartrepo/releases/tag/authelia-0.10.12) when using ingress with Traefik.

fix(authelia): traefik CRD template

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/values.local.yaml
charts/authelia/values.yaml

fix(authelia): cluster ip incorrectly defined

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/templates/deployment.yaml
charts/authelia/templates/persistentVolumeClaim.yaml
charts/authelia/values.local.yaml
charts/authelia/values.yaml

This allows easily adding additional PersistentVolumeClaim's.

fix(authelia): additional pvc's

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/files/configuration.oidc.client.yaml
charts/authelia/templates/_oidc.tpl

This fixes a UX issue where the auth method for various endpoints was cumbersome to configure.
Fixes #296

fix(authelia): oidc endpoint auth method

---

Makefile
charts/authelia/Chart.yaml
charts/authelia/README.md

This is intended on redeploying the chart.

refactor(authelia): redeploy

---

charts/authelia/Chart.yaml
charts/authelia/README.md

This is intended on signing the chart.

feat(authelia): sign

---

charts/authelia/Chart.yaml
charts/authelia/README.md
charts/authelia/values.local.yaml
charts/authelia/values.schema.json
charts/authelia/values.yaml

Fix the missing enable_passkey_login schema description.

fix(authelia): json-schema for passkeys
